// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDq1I2G8YU-nck5ZctFi_1KI3qi9KNf-UE',
    appId: '1:56796743605:web:8fde23743d2d452ba7bbfc',
    messagingSenderId: '56796743605',
    projectId: 'supermarket-delivery-48db2',
    authDomain: 'supermarket-delivery-48db2.firebaseapp.com',
    storageBucket: 'supermarket-delivery-48db2.firebasestorage.app',
    measurementId: 'G-F0NV8XRFT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDxNVlNeXdD6_tqzLJwR4awKPYV8phJPQ',
    appId: '1:56796743605:android:0eb65c4b7a44a18ea7bbfc',
    messagingSenderId: '56796743605',
    projectId: 'supermarket-delivery-48db2',
    storageBucket: 'supermarket-delivery-48db2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCs4Gfx-SEvhvaXLnPOa-2tnjelgPBmzkc',
    appId: '1:56796743605:ios:3ee56a1bd6e5053aa7bbfc',
    messagingSenderId: '56796743605',
    projectId: 'supermarket-delivery-48db2',
    storageBucket: 'supermarket-delivery-48db2.firebasestorage.app',
    iosBundleId: 'com.example.superMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCs4Gfx-SEvhvaXLnPOa-2tnjelgPBmzkc',
    appId: '1:56796743605:ios:3ee56a1bd6e5053aa7bbfc',
    messagingSenderId: '56796743605',
    projectId: 'supermarket-delivery-48db2',
    storageBucket: 'supermarket-delivery-48db2.firebasestorage.app',
    iosBundleId: 'com.example.superMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDq1I2G8YU-nck5ZctFi_1KI3qi9KNf-UE',
    appId: '1:56796743605:web:9c53f3c88ce0d404a7bbfc',
    messagingSenderId: '56796743605',
    projectId: 'supermarket-delivery-48db2',
    authDomain: 'supermarket-delivery-48db2.firebaseapp.com',
    storageBucket: 'supermarket-delivery-48db2.firebasestorage.app',
    measurementId: 'G-QBVKZT43TY',
  );
}
